"""OS-like runtime kernel for model-neutral agent runs."""

from kernel.approval import ApprovalAction, ApprovalDecision, ApprovalPolicy, ApprovalRequest
from kernel.context import RuntimeContext
from kernel.control import ConversationInsert, PauseRequest, RunController, ToolCancelRequest
from kernel.errors import (
    AgentError,
    DuplicateToolError,
    InvalidToolCall,
    LimitExceeded,
    ModelError,
    ModelErrorInfo,
    ModelProviderError,
    ToolError,
)
from kernel.events import AgentEvent, EventEmitter, EventType, EventTypes, QueuedEvent
from kernel.hooks import (
    AfterModelHook,
    AfterToolHook,
    BeforeModelHook,
    BeforeToolHook,
    EventHook,
    ModelErrorDecision,
    ModelErrorHook,
    RuntimeHook,
    TransitionHook,
)
from kernel.journal import JournalRecord, RunJournal
from kernel.limits import LimitReasons, LoopLimits
from kernel.loop import AgentLoop, AgentResult, ToolSchedulerFactory
from kernel.messages import ArtifactRef, ContentPart, Message, ToolCall
from kernel.models import (
    ModelCapabilities,
    ModelClient,
    ModelContentDelta,
    ModelOptions,
    ModelReasoningDelta,
    ModelRequest,
    ModelResponse,
    ModelStreamAccumulator,
    ModelStreamCompleted,
    ModelStreamEvent,
    ModelStreamStarted,
    ModelToolCallDelta,
    ModelUsage,
    ModelUsageDelta,
    ResponseFormat,
    StreamingModelClient,
    ToolChoice,
    model_capabilities,
)
from kernel.resume import PauseSelector, ResumeInput
from kernel.scheduler import (
    ToolBatch,
    ToolCatalog,
    ToolCompleted,
    ToolScheduler,
    ToolSchedulerProtocol,
    ToolStarted,
)
from kernel.snapshot import RunSnapshot
from kernel.state import AgentState, PauseState
from kernel.status import CHECKPOINT_RESUME_STATUSES, TERMINAL_STATUSES, AgentStatus
from kernel.store import CheckpointSummary, RunStore, StoredCheckpoint
from kernel.tools import (
    AcceptableTool,
    BackgroundTask,
    ExecutableTool,
    InvocableTool,
    RuntimeContextSnapshot,
    Tool,
    ToolAcceptance,
    ToolCancelChecker,
    ToolExecutionContext,
    ToolInvocation,
    ToolObservation,
    ToolOutput,
    ToolProgressEmitter,
    ToolRegistryProtocol,
    ToolRejection,
    ToolSpec,
    normalized_tool_risk,
)

__all__ = [
    "AcceptableTool",
    "AfterModelHook",
    "AfterToolHook",
    "AgentError",
    "AgentEvent",
    "AgentLoop",
    "AgentResult",
    "AgentState",
    "AgentStatus",
    "ApprovalAction",
    "ApprovalDecision",
    "ApprovalPolicy",
    "ApprovalRequest",
    "ArtifactRef",
    "BackgroundTask",
    "BeforeModelHook",
    "BeforeToolHook",
    "CHECKPOINT_RESUME_STATUSES",
    "CheckpointSummary",
    "ContentPart",
    "ConversationInsert",
    "DuplicateToolError",
    "EventEmitter",
    "EventHook",
    "EventType",
    "EventTypes",
    "ExecutableTool",
    "InvalidToolCall",
    "InvocableTool",
    "JournalRecord",
    "LimitExceeded",
    "LimitReasons",
    "LoopLimits",
    "Message",
    "ModelCapabilities",
    "ModelClient",
    "ModelContentDelta",
    "ModelError",
    "ModelErrorDecision",
    "ModelErrorHook",
    "ModelErrorInfo",
    "ModelOptions",
    "ModelProviderError",
    "ModelReasoningDelta",
    "ModelRequest",
    "ModelResponse",
    "ModelStreamAccumulator",
    "ModelStreamCompleted",
    "ModelStreamEvent",
    "ModelStreamStarted",
    "ModelToolCallDelta",
    "ModelUsage",
    "ModelUsageDelta",
    "PauseRequest",
    "PauseSelector",
    "PauseState",
    "QueuedEvent",
    "ResponseFormat",
    "ResumeInput",
    "RunController",
    "RunJournal",
    "RunSnapshot",
    "RunStore",
    "RuntimeContext",
    "RuntimeContextSnapshot",
    "RuntimeHook",
    "StoredCheckpoint",
    "StreamingModelClient",
    "TERMINAL_STATUSES",
    "Tool",
    "ToolAcceptance",
    "ToolBatch",
    "ToolCall",
    "ToolCancelChecker",
    "ToolCancelRequest",
    "ToolCatalog",
    "ToolChoice",
    "ToolCompleted",
    "ToolError",
    "ToolExecutionContext",
    "ToolInvocation",
    "ToolObservation",
    "ToolOutput",
    "ToolProgressEmitter",
    "ToolRegistryProtocol",
    "ToolRejection",
    "ToolScheduler",
    "ToolSchedulerFactory",
    "ToolSchedulerProtocol",
    "ToolSpec",
    "ToolStarted",
    "TransitionHook",
    "model_capabilities",
    "normalized_tool_risk",
]
